import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/lib/reduxProvider";
import { Gloock, Gochi_Hand } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const glook = Gloock({
  weight: ['400'],
  subsets: ['cyrillic-ext'],
  variable: '--font-glook', // <- add variable
})

const gochi = Gochi_Hand({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-gochi', // <- add variable
})

export const metadata: Metadata = {
  title: "collect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      <body
        className={`${gochi.variable} ${glook.variable} antialiased`}>
        <QueryClientProvider client={queryClient}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
